project_id = "vlhxdymzlheicmambywu"

[functions.send-contact-email]
verify_jwt = false

[functions.track-page-view]
verify_jwt = false

[functions.capture-lead]
verify_jwt = false

[functions.track-user-event]
verify_jwt = false

[functions.send-scorecard-email]
verify_jwt = false
