project_id = "vlhxdymzlheicmambywu"

[functions.send-contact-email]
verify_jwt = false

[functions.track-page-view]
verify_jwt = false

[functions.capture-lead]
verify_jwt = false

[functions.track-user-event]
verify_jwt = false

[functions.send-scorecard-email]
verify_jwt = false

[functions.issue-certificate]
verify_jwt = false

[functions.track-certificate-interaction]
verify_jwt = false

[functions.complete-course]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false
